"""empty message

Revision ID: d84e531d6018
Revises: 
Create Date: 2020-06-21 23:57:44.162891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84e531d6018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ctime', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mtime', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_uuid'], ['role.uuid'], name='user_role_uuid_fkey'),
    sa.ForeignKeyConstraint(['status_uuid'], ['status.uuid'], name='user_status_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('uuid', name='user_uuid_key')
    )
    # ### end Alembic commands ###
